---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - сайт должен соответствовать законодательству
  - неавторизавнный пользователь может пройти "Простую битву"
  - оформлять заказ может только зарегистрированный и авторизованный  пользователь
  - поля для ввода должны быть валидными
  - при оформлении заказа у пользователя должны быть указаны контактные данные (телефон,почта,адрес доставки)
  - цена товара не может быть  нулем или отрицательным числом
  - нельзя создать игру для неавторизованного пользователя
  - при смене языка с Английского на русский  все элементы страницы на своих местах
  - при смене языка с Английского на русский  все слова (кроме брендов) переводятся корректно


