---
functional:
  - Пользователь должен иметь возможность авторизоваться через Gitgu, Discort
  - Пользователь должен иметь возможность зарегистрироваться и авторизоваться по логину и паролю
  - Авторизованный пользователь должен иметь возможность создавать игру
  - Авторизованный пользователь должен иметь возможность отправлять сообщение в чат
  - Авторизованный пользователь должен иметь возможность просматривать вкладки LOBBY,TOURNAMENTS, HISTORY, Top list
  - неавторизавнный пользователь может пройти "Простую битву"
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - сайт должен соответствовать законодательству
  - Даты и время должны отображаться в часовом поясе пользователя (а не сервера)
  - Если пользователь вышел из системы, редактор кода должен сохранить написанный код в LocalStorage
  - Если задача решена неверно, кнопка "Отправить" должна блокироваться на 3 секунды (чтобы избежать флуда)

