---
functional:
  - Пользователь должен иметь возможность авторизоваться через Github, Discort
  - Пользователь должен иметь возможность зарегистрироваться и авторизоваться по логину и паролю
  - Авторизованный пользователь должен иметь возможность создавать игру с выобором сложности, языка и времени прохождения игры
  - Авторизованный пользователь должен иметь возможность отправлять сообщение в общий чат
  - Авторизованный пользователь должен иметь возможность отправлять сообщение в чат внутри игры
  - Авторизованный пользователь должен иметь возможность просматривать и редактировать свой профиль
  - Авторизованный пользователь должен иметь возможность приглашать других пользователей в  свою игру
  - Авторизованный пользователь должен иметь возможность принимать/отклюнять приглашения на игру от других пользователей
  - Авторизованный пользователь должен иметь возможность присоединиться к открытой игре
  - Неавторизавнный пользователь должен иметь возможность пройти "Простую битву"

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - сайт должен соответствовать законодательству
  - Даты и время должны отображаться в часовом поясе пользователя (а не сервера)
  - Если пользователь вышел из системы, редактор кода должен сохранить написанный код в LocalStorage
  - Если задача решена неверно, кнопка "Отправить" должна блокироваться на 3 секунды (чтобы избежать флуда)
  - Если пользователь закрывает вкладку во время баттла, система должна сохранить его прогресс.

